name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npx changelogithub # or changelogithub@0.12 if ensure the stable result
        env:
          GITHUB_TOKEN: ${{secrets.WXBOT_TOKEN}}

  release:
    needs: changelog
    strategy:
      matrix:
        platform: [ubuntu-latest]

    name: Release
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "19"
          registry-url: "https://registry.npmjs.org"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          path: wxbot-web
          persist-credentials: false
          fetch-depth: 0
          submodules: recursive

      - name: Build
        run: |
          mv wxbot-web/build.sh .
          bash build.sh
          
      - name: Upload dist files
        uses: ad-m/github-push-action@master
        with:
          branch: main
          directory: wxbot-web

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: compress/*.tar.gz
